blank_issues_enabled: false
contact_links:
  - name: Home Assistant Community
    url: https://community.home-assistant.io/
    about: Ask questions and discuss with the wider Home Assistant community
  - name: NSW Beachwatch Official Website
    url: https://www.beachwatch.nsw.gov.au/
    about: Official NSW Government Beachwatch information and data
